---
title: "ISLR_Chap_a13"
format: html
editor: visual
---

```{r}
set.seed(6)
x <- matrix(rnorm(10 * 100), 10, 100)
x[ , 1:50] <- x[ , 1:50] + 0.5
```

```{r}
t.test(x[ ,1], mu = 0)
```

```{r}
p.values <- rep(0, 100)
for(i in 1:100){
  p.values[i] <- t.test(x[, i], mu = 0)$p.value
}
decision <- rep("Do Not Reject H-naught", 100)
decision[p.values <= .05] <- "Reject H-naught"
```

```{r}
table(decision, c(rep("H-naught false", 50), rep("H-naught true", 50)))
```

```{r}
library(ISLR2)
attach(Khan)

x <- rbind(xtrain, xtest)

y <- c(as.numeric(ytrain), as.numeric(ytest))

x <- as.matrix(x)

x1 <- x[which(y == 2), ]
x2 <- x[which(y == 4), ] 
n1 <- nrow(x1) 
n2 <- nrow(x2) 
t.out <- t.test(x1[, 11], x2[, 11], var.equal = TRUE) 
TT <- t.out$statistic 

TT
```

```{r}
t.out$p.value
```

```{r}
set.seed(1)
B <- 10000
Tbs <- rep(NA, B)

for(b in 1:B){
  dat <- sample(c(x1[, 11], x2[, 11]))
  Tbs[b] <- t.test(dat[1:n1], dat[(n1 + 1):(n1 + n2)], var.equal = TRUE)$statistic
}
mean((abs(Tbs) >= abs(TT)))
```
